version: '3.8'
services:
  fe-app:
    # image: fe-container:first
    image: registry.cn-hangzhou.aliyuncs.com/xiaochen_image/xiaochen:aaa
    ports:
      - 81:81
    depends_on:
      - nest-app
    networks:
      - common-network
  user-app:
    # image: fe-container:first
    image: registry.cn-hangzhou.aliyuncs.com/xiaochen_image/xiaochen:bbb
    ports:
      - 82:82
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    # ports:
    #   - 3000:3000
    restart: always
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/pmd-mobile/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置默认字符集
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: xiaochen
    ports:
      - "3306:3306"
    restart: always
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/pmd-mobile/code/
    ports:
      - "6379:6379"
    restart: always
    networks:
      - common-network
  minio-container:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - /User/pmd-mobile/data:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: xiaochen
      MINIO_ROOT_PASSWORD: 123456789
    restart: always
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
