version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3000:3000
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/pmd-mobile/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: xiaochen
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/pmd-mobile/code/
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
